import React, { useEffect, useState } from 'react';
import api from '../services/api';
import { useGuide } from '../contexts/GuideContext';
import {
  Box,
  Typography,
  Card,
  CardContent,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  Button,
  CircularProgress,
  Pagination,
  TextField,
  MenuItem,
  Alert,
  AlertTitle,
} from '@mui/material';
import { InfoOutlined as InfoIcon } from '@mui/icons-material';

const AlertsPage = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [resolvedFilter, setResolvedFilter] = useState('N');

  const { guideMode } = useGuide();

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const res = await api.get('/alerts', {
        params: { page, pageSize: 15, resolved: resolvedFilter },
      });
      setAlerts(res.data.data.data || []);
      setTotalPages(res.data.data.totalPages || 1);
    } catch (err) {
      console.error('Fetch alerts error:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [page, resolvedFilter]);

  const handleResolve = async (id) => {
    try {
      await api.patch(`/alerts/${id}/resolve`, { remarks: 'Resolved by control room supervisor' });
      fetchAlerts();
    } catch (err) {
      alert(err.response?.data?.message || 'Resolve alert failed');
    }
  };

  return (
    <Box>
      {/* Module Overview Banner */}
      {guideMode && (
        <Alert
          icon={<InfoIcon fontSize="inherit" />}
          severity="info"
          sx={{
            mb: 3,
            backgroundColor: 'rgba(30, 58, 138, 0.25)',
            border: '1px solid rgba(59, 130, 246, 0.3)',
            color: '#f8fafc',
            '& .MuiAlert-icon': { color: '#60a5fa' },
          }}
        >
          <AlertTitle sx={{ fontWeight: 700, fontSize: '1rem', color: '#93c5fd' }}>
            Security System Alert Center Guide
          </AlertTitle>
          <Typography variant="body2" sx={{ fontSize: '0.875rem', opacity: 0.9 }}>
            This operational module tracks automatically generated security exceptions, offline device alerts, vacant critical posts, and unauthorized access attempts.
          </Typography>
          <Box display="flex" gap={2} flexWrap="wrap" sx={{ mt: 1, pt: 0.5, borderTop: '1px dashed rgba(255,255,255,0.1)', fontSize: '0.8rem' }}>
            <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
              • <strong>CRITICAL / HIGH / MEDIUM:</strong> Severities generated by background cron jobs and hardware services.
            </Typography>
            <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
              • <strong>Resolution Workflow:</strong> Supervisors review alerts, enter resolution remarks, and close the incident.
            </Typography>
          </Box>
        </Alert>
      )}

      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 700 }}>
            Security Alert Center
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Incident alerts, vacant post notifications, and hardware exception logs
          </Typography>
        </Box>
      </Box>

      <Card sx={{ mb: 3 }}>
        <CardContent>
          <TextField
            select
            label="Filter Resolution Status"
            size="small"
            value={resolvedFilter}
            onChange={(e) => {
              setResolvedFilter(e.target.value);
              setPage(1);
            }}
            sx={{ minWidth: 200 }}
          >
            <MenuItem value="N">Unresolved Alerts</MenuItem>
            <MenuItem value="Y">Resolved Alerts</MenuItem>
            <MenuItem value="">All Alerts</MenuItem>
          </TextField>
        </CardContent>
      </Card>

      <Card>
        <CardContent sx={{ p: 0 }}>
          <TableContainer component={Paper} elevation={0} sx={{ bgcolor: 'transparent' }}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Alert Time</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Alert Message</TableCell>
                  <TableCell align="center" sx={{ fontWeight: 600 }}>Severity</TableCell>
                  <TableCell align="center" sx={{ fontWeight: 600 }}>Status</TableCell>
                  <TableCell align="center" sx={{ fontWeight: 600 }}>Action</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={5} align="center" sx={{ py: 4 }}>
                      <CircularProgress size={30} />
                    </TableCell>
                  </TableRow>
                ) : alerts.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={5} align="center" sx={{ py: 4, color: 'text.secondary' }}>
                      No alerts recorded.
                    </TableCell>
                  </TableRow>
                ) : (
                  alerts.map((alt) => (
                    <TableRow key={alt.AlertCode} hover>
                      <TableCell sx={{ fontWeight: 600 }}>
                        {new Date(alt.AlertDateTime).toLocaleString()}
                      </TableCell>
                      <TableCell sx={{ maxWidth: 320 }}>{alt.AlertMessage}</TableCell>
                      <TableCell align="center">
                        <Chip
                          label={alt.Severity}
                          size="small"
                          color={alt.Severity === 'CRITICAL' ? 'error' : 'warning'}
                          sx={{ height: 20, fontSize: '0.7rem' }}
                        />
                      </TableCell>
                      <TableCell align="center">
                        <Chip
                          label={alt.Resolved === 'Y' ? 'RESOLVED' : 'UNRESOLVED'}
                          size="small"
                          color={alt.Resolved === 'Y' ? 'success' : 'error'}
                          sx={{ height: 20, fontSize: '0.7rem' }}
                        />
                      </TableCell>
                      <TableCell align="center">
                        {alt.Resolved === 'N' && (
                          <Button
                            variant="outlined"
                            color="success"
                            size="small"
                            onClick={() => handleResolve(alt.AlertCode)}
                          >
                            Resolve Alert
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </TableContainer>

          <Box display="flex" justifyContent="center" p={2}>
            <Pagination count={totalPages} page={page} onChange={(e, p) => setPage(p)} color="primary" />
          </Box>
        </CardContent>
      </Card>
    </Box>
  );
};

export default AlertsPage;
