import React, { useEffect, useState } from 'react';
import api from '../services/api';
import { useGuide } from '../contexts/GuideContext';
import {
  Box,
  Typography,
  Card,
  CardContent,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  Button,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  MenuItem,
  CircularProgress,
  Pagination,
  Alert,
  AlertTitle,
} from '@mui/material';
import { Add as AddIcon, InfoOutlined as InfoIcon } from '@mui/icons-material';

const DeploymentPage = () => {
  const [deployments, setDeployments] = useState([]);
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [openModal, setOpenModal] = useState(false);

  const { guideMode } = useGuide();

  const [formData, setFormData] = useState({
    deploymentDate: new Date().toISOString().split('T')[0],
    empNo: '',
    postCode: '',
    shiftCode: 1,
    remarks: '',
  });

  const fetchDeployments = async () => {
    setLoading(true);
    try {
      const res = await api.get('/deployments', { params: { page, pageSize: 15 } });
      setDeployments(res.data.data.data || []);
      setTotalPages(res.data.data.totalPages || 1);
    } catch (err) {
      console.error('Fetch deployments error:', err);
    } finally {
      setLoading(false);
    }
  };

  const fetchPosts = async () => {
    try {
      const res = await api.get('/posts');
      setPosts(res.data.data || []);
    } catch (err) {
      console.error('Fetch posts error:', err);
    }
  };

  useEffect(() => {
    fetchDeployments();
    fetchPosts();
  }, [page]);

  const handleManualAllocation = async () => {
    try {
      await api.post('/deployments', formData);
      setOpenModal(false);
      fetchDeployments();
    } catch (err) {
      alert(err.response?.data?.message || 'Manual deployment failed');
    }
  };

  return (
    <Box>
      {/* Module Overview Banner */}
      {guideMode && (
        <Alert
          icon={<InfoIcon fontSize="inherit" />}
          severity="info"
          sx={{
            mb: 3,
            backgroundColor: 'rgba(30, 58, 138, 0.25)',
            border: '1px solid rgba(59, 130, 246, 0.3)',
            color: '#f8fafc',
            '& .MuiAlert-icon': { color: '#60a5fa' },
          }}
        >
          <AlertTitle sx={{ fontWeight: 700, fontSize: '1rem', color: '#93c5fd' }}>
            Guard Post Deployments Module Guide
          </AlertTitle>
          <Typography variant="body2" sx={{ fontSize: '0.875rem', opacity: 0.9 }}>
            This module manages active guard allocations across all security duty posts. Allocations are automatically generated by the engine or manually assigned by supervisors.
          </Typography>
          <Box display="flex" gap={2} flexWrap="wrap" sx={{ mt: 1, pt: 0.5, borderTop: '1px dashed rgba(255,255,255,0.1)', fontSize: '0.8rem' }}>
            <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
              • <strong>AUTO vs MANUAL:</strong> Auto allocations use algorithm parameters. Supervisors can override with manual deployment.
            </Typography>
            <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
              • <strong>Deployment Lifecycle:</strong> ALLOCATED ➔ REPORTED (at post) ➔ COMPLETED (shift end).
            </Typography>
            <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
              • <strong>Audit History:</strong> Every deployment change is logged in <code>securitydeploymenthistory</code> for compliance.
            </Typography>
          </Box>
        </Alert>
      )}

      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Box>
          <Typography variant="h4" sx={{ fontWeight: 700 }}>
            Security Post Deployments
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Manage guard post allocations and deployment lifecycles
          </Typography>
        </Box>
        <Button
          variant="contained"
          color="primary"
          startIcon={<AddIcon />}
          onClick={() => setOpenModal(true)}
        >
          Manual Guard Deployment
        </Button>
      </Box>

      <Card>
        <CardContent sx={{ p: 0 }}>
          <TableContainer component={Paper} elevation={0} sx={{ bgcolor: 'transparent' }}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>Deployment Date</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Guard Personnel</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Assigned Post</TableCell>
                  <TableCell align="center" sx={{ fontWeight: 600 }}>Shift</TableCell>
                  <TableCell align="center" sx={{ fontWeight: 600 }}>Method</TableCell>
                  <TableCell align="center" sx={{ fontWeight: 600 }}>Status</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={6} align="center" sx={{ py: 4 }}>
                      <CircularProgress size={30} />
                    </TableCell>
                  </TableRow>
                ) : deployments.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} align="center" sx={{ py: 4, color: 'text.secondary' }}>
                      No active deployments recorded.
                    </TableCell>
                  </TableRow>
                ) : (
                  deployments.map((row) => (
                    <TableRow key={row.DeploymentCode} hover>
                      <TableCell sx={{ fontWeight: 600 }}>
                        {new Date(row.DeploymentDate).toLocaleDateString()}
                      </TableCell>
                      <TableCell>
                        <Typography variant="body2" sx={{ fontWeight: 600 }}>
                          {row.employee?.FirstName} {row.employee?.LastName}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          Emp #{row.EmpNo} ({row.employee?.Gender === 'F' ? 'Female' : 'Male'})
                        </Typography>
                      </TableCell>
                      <TableCell>
                        <Typography variant="body2" sx={{ fontWeight: 600 }}>
                          {row.post?.PostName}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          {row.post?.postCategory?.PostCategoryName}
                        </Typography>
                      </TableCell>
                      <TableCell align="center">Shift {row.ShiftCode}</TableCell>
                      <TableCell align="center">
                        <Chip
                          label={row.AllocationMethod || 'AUTO'}
                          size="small"
                          color={row.AllocationMethod === 'AUTO' ? 'primary' : 'secondary'}
                          sx={{ height: 20, fontSize: '0.7rem' }}
                        />
                      </TableCell>
                      <TableCell align="center">
                        <Chip
                          label={row.DeploymentStatus}
                          size="small"
                          color={
                            row.DeploymentStatus === 'REPORTED'
                              ? 'success'
                              : row.DeploymentStatus === 'ALLOCATED'
                              ? 'info'
                              : 'default'
                          }
                          sx={{ height: 20, fontSize: '0.7rem' }}
                        />
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </TableContainer>

          <Box display="flex" justifyContent="center" p={2}>
            <Pagination count={totalPages} page={page} onChange={(e, p) => setPage(p)} color="primary" />
          </Box>
        </CardContent>
      </Card>

      {/* Manual Deployment Modal */}
      <Dialog open={openModal} onClose={() => setOpenModal(false)} maxWidth="sm" fullWidth>
        <DialogTitle sx={{ fontWeight: 700 }}>Manual Guard Post Deployment</DialogTitle>
        <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 2 }}>
          <TextField
            label="Deployment Date"
            type="date"
            fullWidth
            value={formData.deploymentDate}
            onChange={(e) => setFormData({ ...formData, deploymentDate: e.target.value })}
            InputLabelProps={{ shrink: true }}
          />
          <TextField
            label="Employee Number (EmpNo)"
            fullWidth
            value={formData.empNo}
            onChange={(e) => setFormData({ ...formData, empNo: e.target.value })}
            placeholder="e.g. 1005"
          />
          <TextField
            select
            label="Duty Post"
            fullWidth
            value={formData.postCode}
            onChange={(e) => setFormData({ ...formData, postCode: e.target.value })}
          >
            {posts.map((p) => (
              <MenuItem key={p.PostCode} value={p.PostCode}>
                {p.PostName} (Priority {p.Priority}) {p.FemaleOnly === 'Y' ? '[Female Only]' : ''}
              </MenuItem>
            ))}
          </TextField>
          <TextField
            select
            label="Shift"
            fullWidth
            value={formData.shiftCode}
            onChange={(e) => setFormData({ ...formData, shiftCode: e.target.value })}
          >
            <MenuItem value={1}>Morning Shift (A)</MenuItem>
            <MenuItem value={2}>Afternoon Shift (B)</MenuItem>
            <MenuItem value={3}>Night Shift (C)</MenuItem>
          </TextField>
          <TextField
            label="Supervisor Remarks"
            fullWidth
            multiline
            rows={2}
            value={formData.remarks}
            onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
          />
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2 }}>
          <Button onClick={() => setOpenModal(false)}>Cancel</Button>
          <Button variant="contained" onClick={handleManualAllocation}>
            Confirm Manual Allocation
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default DeploymentPage;
