import React, { useState } from 'react';
import api from '../services/api';
import { useGuide } from '../contexts/GuideContext';
import { useAuth } from '../contexts/AuthContext';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

import {
  Box,
  Typography,
  Card,
  CardContent,
  Grid,
  TextField,
  Button,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  CircularProgress,
  MenuItem,
  Alert,
  AlertTitle,
  Tooltip,
} from '@mui/material';
import {
  Download as ExportIcon,
  PictureAsPdf as PdfIcon,
  TableChart as ExcelIcon,
  Print as PrintIcon,
  InfoOutlined as InfoIcon,
  Assessment as AssessmentIcon,
} from '@mui/icons-material';

const ReportsPage = () => {
  const [reportType, setReportType] = useState('attendance');
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);

  const { guideMode } = useGuide();
  const { user } = useAuth();

  const handleGenerateReport = async () => {
    setLoading(true);
    try {
      const res = await api.get(`/reports/${reportType}`, {
        params: { startDate, endDate },
      });
      setData(res.data.data || []);
    } catch (err) {
      console.error('Report generation error:', err);
    } finally {
      setLoading(false);
    }
  };

  const getReportTitle = () => {
    switch (reportType) {
      case 'attendance':
        return 'Biometric Attendance Audit Report';
      case 'deployment':
        return 'Guard Post Deployment Audit Report';
      case 'vacancy':
        return 'Duty Post Vacancy History Report';
      default:
        return 'Security Operational Report';
    }
  };

  // 1. Export Report to PDF
  const exportToPDF = () => {
    if (data.length === 0) return;

    const doc = new jsPDF('p', 'pt', 'a4');
    const title = getReportTitle();
    const generatedBy = `${user?.firstName || 'Admin'} ${user?.lastName || ''}`.trim();
    const generatedTime = new Date().toLocaleString();

    // Document Header & Letterhead
    doc.setFillColor(15, 23, 42); // Dark Slate Header background
    doc.rect(0, 0, 595.28, 70, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('AUTOMATED SECURITY PERSONNEL POST ALLOCATION SYSTEM', 40, 32);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text('OFFICIAL SECURITY OPERATIONS AUDIT & COMPLIANCE REPORT', 40, 48);

    // Report Title & Metadata Box
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 40, 100);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(`Date Range: ${startDate} to ${endDate}`, 40, 116);
    doc.text(`Generated On: ${generatedTime}`, 300, 116);
    doc.text(`Total Records: ${data.length}`, 40, 130);
    doc.text(`Generated By: ${generatedBy} (${user?.role || 'SUPERADMIN'})`, 300, 130);

    doc.setDrawColor(226, 232, 240);
    doc.line(40, 140, 555, 140);

    // Prepare Table Headers & Data based on Report Type
    let head = [];
    let body = [];

    if (reportType === 'attendance') {
      head = [['#', 'Date & Time', 'Guard Personnel', 'Biometric Device', 'Shift', 'Type', 'Status']];
      body = data.map((row, idx) => [
        idx + 1,
        new Date(row.PunchDateTime).toLocaleString(),
        `${row.employee?.FirstName || ''} ${row.employee?.LastName || ''} (#${row.EmpNo})`,
        row.device?.DeviceName || `Reader #${row.DeviceCode}`,
        `Shift ${row.ShiftCode}`,
        row.PunchType || 'IN',
        row.AttendanceStatus,
      ]);
    } else if (reportType === 'deployment') {
      head = [['#', 'Deployment Date', 'Guard Personnel', 'Assigned Post', 'Shift', 'Method', 'Status']];
      body = data.map((row, idx) => [
        idx + 1,
        new Date(row.DeploymentDate).toLocaleDateString(),
        `${row.employee?.FirstName || ''} ${row.employee?.LastName || ''} (#${row.EmpNo})`,
        row.post?.PostName || `Post #${row.PostCode}`,
        `Shift ${row.ShiftCode}`,
        row.AllocationMethod || 'AUTO',
        row.DeploymentStatus,
      ]);
    } else if (reportType === 'vacancy') {
      head = [['#', 'Vacancy Date', 'Duty Post Name', 'Category', 'Req', 'Alloc', 'Vacant', 'Status']];
      body = data.map((row, idx) => [
        idx + 1,
        new Date(row.VacancyDate).toLocaleDateString(),
        row.post?.PostName || `Post #${row.PostCode}`,
        row.post?.postCategory?.PostCategoryName || 'N/A',
        row.RequiredGuards,
        row.AllocatedGuards,
        row.VacantGuards,
        row.Status,
      ]);
    }

    autoTable(doc, {
      head,
      body,
      startY: 155,
      theme: 'grid',
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontSize: 8.5,
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 8,
        cellPadding: 6,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      didDrawPage: () => {
        // Footer Page Numbering
        const str = `Page ${doc.internal.getNumberOfPages()}`;
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(str, 520, 820);
        doc.text('Confidential - SPPAS Automated Security Personnel Post Allocation System', 40, 820);
      },
    });

    const filename = `SPPAS_${reportType.toUpperCase()}_REPORT_${startDate}_TO_${endDate}.pdf`;
    doc.save(filename);
  };

  // 2. Export Report to Excel (.xlsx)
  const exportToExcel = () => {
    if (data.length === 0) return;

    let excelData = [];

    if (reportType === 'attendance') {
      excelData = data.map((row, idx) => ({
        'S.No': idx + 1,
        'Punch Date': new Date(row.PunchDateTime).toLocaleDateString(),
        'Punch Time': new Date(row.PunchDateTime).toLocaleTimeString(),
        'Emp No': row.EmpNo,
        'Guard Name': `${row.employee?.FirstName || ''} ${row.employee?.LastName || ''}`.trim(),
        Gender: row.employee?.Gender === 'F' ? 'Female' : 'Male',
        'Device Terminal': row.device?.DeviceName || `Reader #${row.DeviceCode}`,
        Shift: `Shift ${row.ShiftCode}`,
        'Punch Type': row.PunchType || 'IN',
        Status: row.AttendanceStatus,
        Remarks: row.Remarks || '',
      }));
    } else if (reportType === 'deployment') {
      excelData = data.map((row, idx) => ({
        'S.No': idx + 1,
        'Deployment Date': new Date(row.DeploymentDate).toLocaleDateString(),
        'Emp No': row.EmpNo,
        'Guard Name': `${row.employee?.FirstName || ''} ${row.employee?.LastName || ''}`.trim(),
        'Assigned Post': row.post?.PostName || `Post #${row.PostCode}`,
        Category: row.post?.postCategory?.PostCategoryName || '',
        Shift: `Shift ${row.ShiftCode}`,
        'Allocation Method': row.AllocationMethod || 'AUTO',
        Status: row.DeploymentStatus,
      }));
    } else if (reportType === 'vacancy') {
      excelData = data.map((row, idx) => ({
        'S.No': idx + 1,
        'Vacancy Date': new Date(row.VacancyDate).toLocaleDateString(),
        'Duty Post Name': row.post?.PostName || `Post #${row.PostCode}`,
        Category: row.post?.postCategory?.PostCategoryName || '',
        'Required Guards': row.RequiredGuards,
        'Allocated Guards': row.AllocatedGuards,
        'Vacant Guards': row.VacantGuards,
        Status: row.Status,
      }));
    }

    const worksheet = XLSX.utils.json_to_sheet(excelData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Security Report');

    const filename = `SPPAS_${reportType.toUpperCase()}_REPORT_${startDate}_TO_${endDate}.xlsx`;
    XLSX.writeFile(workbook, filename);
  };

  // 3. Print Hard Copy (Print-optimized Dialog)
  const handlePrint = () => {
    window.print();
  };

  return (
    <Box sx={{ '@media print': { color: '#000', bgcolor: '#fff' } }}>
      {/* Hide guidance banners during physical paper printing */}
      <Box sx={{ '@media print': { display: 'none' } }}>
        {guideMode && (
          <Alert
            icon={<InfoIcon fontSize="inherit" />}
            severity="info"
            sx={{
              mb: 3,
              backgroundColor: 'rgba(30, 58, 138, 0.25)',
              border: '1px solid rgba(59, 130, 246, 0.3)',
              color: '#f8fafc',
              '& .MuiAlert-icon': { color: '#60a5fa' },
            }}
          >
            <AlertTitle sx={{ fontWeight: 700, fontSize: '1rem', color: '#93c5fd' }}>
              System Audit & Operational Reports Guide
            </AlertTitle>
            <Typography variant="body2" sx={{ fontSize: '0.875rem', opacity: 0.9 }}>
              Generate compliance and operational reports across custom date ranges for attendance streams, guard deployment logs, and duty post vacancy trends.
            </Typography>
            <Box display="flex" gap={2} flexWrap="wrap" sx={{ mt: 1, pt: 0.5, borderTop: '1px dashed rgba(255,255,255,0.1)', fontSize: '0.8rem' }}>
              <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
                • <strong>Export PDF:</strong> Formatted official PDF report with header letterhead for formal submission.
              </Typography>
              <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
                • <strong>Export Excel:</strong> Spreadsheet workbook (.xlsx) formatted for Excel data analysis.
              </Typography>
              <Typography variant="caption" sx={{ color: '#bfdbfe' }}>
                • <strong>Print Hard Copy:</strong> Print-optimized layout formatted for physical paper printers.
              </Typography>
            </Box>
          </Alert>
        )}

        <Box display="flex" justifyContent="space-between" alignItems="center" mb={3} flexWrap="wrap" gap={2}>
          <Box>
            <Typography variant="h4" sx={{ fontWeight: 700 }}>
              System Audit & Operational Reports
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Generate attendance, post deployment, and vacancy compliance reports
            </Typography>
          </Box>

          {data.length > 0 && (
            <Box display="flex" gap={1.5} flexWrap="wrap">
              <Button
                variant="contained"
                color="error"
                startIcon={<PdfIcon />}
                onClick={exportToPDF}
              >
                Export to PDF
              </Button>
              <Button
                variant="contained"
                color="success"
                startIcon={<ExcelIcon />}
                onClick={exportToExcel}
              >
                Export to Excel
              </Button>
              <Button
                variant="outlined"
                color="info"
                startIcon={<PrintIcon />}
                onClick={handlePrint}
              >
                Print Hard Copy
              </Button>
            </Box>
          )}
        </Box>

        <Card sx={{ mb: 3 }}>
          <CardContent sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center' }}>
            <TextField
              select
              label="Report Category"
              size="small"
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              sx={{ minWidth: 240 }}
            >
              <MenuItem value="attendance">Biometric Attendance Audit</MenuItem>
              <MenuItem value="deployment">Guard Post Deployment Audit</MenuItem>
              <MenuItem value="vacancy">Duty Post Vacancy History</MenuItem>
            </TextField>

            <TextField
              label="Start Date"
              type="date"
              size="small"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              InputLabelProps={{ shrink: true }}
            />

            <TextField
              label="End Date"
              type="date"
              size="small"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              InputLabelProps={{ shrink: true }}
            />

            <Button
              variant="contained"
              color="primary"
              onClick={handleGenerateReport}
              startIcon={loading ? <CircularProgress size={18} color="inherit" /> : <AssessmentIcon />}
              disabled={loading}
            >
              Generate Report
            </Button>
          </CardContent>
        </Card>
      </Box>

      {/* Printable Report View (Visible both in Browser and Physical Printer) */}
      <Card sx={{ '@media print': { boxShadow: 'none', bgcolor: 'transparent' } }}>
        <CardContent sx={{ p: 0 }}>
          {/* Printable Document Letterhead Header (Only displays during printing or report display) */}
          <Box sx={{ display: 'none', '@media print': { display: 'block', mb: 3 } }}>
            <Typography variant="h5" sx={{ fontWeight: 800, textTransform: 'uppercase' }}>
              Automated Security Personnel Post Allocation System
            </Typography>
            <Typography variant="subtitle2" sx={{ color: '#475569' }}>
              Official Security Operations Audit & Compliance Report
            </Typography>
            <Box display="flex" justifyContent="space-between" mt={2} pt={1} sx={{ borderTop: '2px solid #000', fontSize: '0.85rem' }}>
              <Typography variant="body2"><strong>Report Category:</strong> {getReportTitle()}</Typography>
              <Typography variant="body2"><strong>Date Range:</strong> {startDate} to {endDate}</Typography>
              <Typography variant="body2"><strong>Total Records:</strong> {data.length}</Typography>
            </Box>
          </Box>

          <TableContainer component={Paper} elevation={0} sx={{ bgcolor: 'transparent' }}>
            <Table size="small">
              <TableHead>
                {reportType === 'attendance' ? (
                  <TableRow>
                    <TableCell sx={{ fontWeight: 700 }}>#</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Punch Date & Time</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Guard Personnel</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Biometric Device</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Shift</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Type</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Status</TableCell>
                  </TableRow>
                ) : reportType === 'deployment' ? (
                  <TableRow>
                    <TableCell sx={{ fontWeight: 700 }}>#</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Deployment Date</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Guard Personnel</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Assigned Duty Post</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Shift</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Method</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Status</TableCell>
                  </TableRow>
                ) : (
                  <TableRow>
                    <TableCell sx={{ fontWeight: 700 }}>#</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Vacancy Date</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Duty Post Name</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Category</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Required</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Allocated</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Vacant</TableCell>
                    <TableCell align="center" sx={{ fontWeight: 700 }}>Status</TableCell>
                  </TableRow>
                )}
              </TableHead>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={7} align="center" sx={{ py: 4 }}>
                      <CircularProgress size={30} />
                    </TableCell>
                  </TableRow>
                ) : data.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} align="center" sx={{ py: 4, color: 'text.secondary' }}>
                      No report records generated for selected range. Select options above and click "Generate Report".
                    </TableCell>
                  </TableRow>
                ) : (
                  data.map((row, idx) => (
                    <TableRow key={idx} hover>
                      <TableCell sx={{ fontWeight: 600 }}>{idx + 1}</TableCell>
                      <TableCell sx={{ fontWeight: 600 }}>
                        {reportType === 'attendance'
                          ? new Date(row.PunchDateTime).toLocaleString()
                          : reportType === 'deployment'
                          ? new Date(row.DeploymentDate).toLocaleDateString()
                          : new Date(row.VacancyDate).toLocaleDateString()}
                      </TableCell>
                      <TableCell>
                        {row.employee ? `${row.employee.FirstName} ${row.employee.LastName} (#${row.EmpNo})` : row.post?.PostName}
                      </TableCell>
                      <TableCell>
                        {reportType === 'attendance'
                          ? row.device?.DeviceName || `Reader #${row.DeviceCode}`
                          : reportType === 'deployment'
                          ? row.post?.PostName
                          : row.post?.postCategory?.PostCategoryName}
                      </TableCell>
                      {reportType !== 'vacancy' ? (
                        <>
                          <TableCell align="center">Shift {row.ShiftCode}</TableCell>
                          <TableCell align="center">{row.PunchType || row.AllocationMethod || 'AUTO'}</TableCell>
                          <TableCell align="center">{row.AttendanceStatus || row.DeploymentStatus}</TableCell>
                        </>
                      ) : (
                        <>
                          <TableCell align="center">{row.RequiredGuards}</TableCell>
                          <TableCell align="center">{row.AllocatedGuards}</TableCell>
                          <TableCell align="center">{row.VacantGuards}</TableCell>
                          <TableCell align="center">{row.Status}</TableCell>
                        </>
                      )}
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </TableContainer>
        </CardContent>
      </Card>
    </Box>
  );
};

export default ReportsPage;
